version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: d1111
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: Saas-Dashboard
    # Bind mount for local folder ./db_data
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: saas-backend
    depends_on:
      - db
    ports:
      - "7073:7073"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: d1111
      DB_PASSWORD: mypassword
      DB_NAME: Saas-Dashboard

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saas-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
